services:
  app:
    build: .
    command: python -u app.py
    ports:
      - "8080:5000"
    volumes:
      - ./content.txt:/app/content.txt
    depends_on:
      - db

  db:
    image: mongo
    hostname: td6_mongodb
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro